# These are supported funding model platforms

github: ne-utka
open_collective: # Replace with a single Open Collective username
thanks_dev: Marallys
custom: ItsReizy, Bumchik_, qaadept, Yl7oPoTblU_KoT
