name: emotecraft
description: "${description}"
main: io.github.kosmx.emotes.bukkit.BukkitWrapper
version: ${version}
api-version: ${mcversion}
website: https://docs.zigythebird.com/emotecraft/gettingstarted
authors: [KomsX, dima_dencep]
folia-supported: true
